// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Group.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;

namespace CommunicationModels.Models
{
    /// <summary>Holder for reflection information generated from Group.proto</summary>
    public static partial class GroupReflection
    {

        #region Descriptor
        /// <summary>File descriptor for Group.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static GroupReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "CgtHcm91cC5wcm90bxIaQ29tbXVuaWNhdGlvbk1vZGVscy5Nb2RlbHMiTAoF",
                  "R3JvdXASDQoFdGl0bGUYASABKAkSEAoIZ3JvdXBLZXkYAiABKAkSFAoMdXNl",
                  "ckdyb3VwS2V5GAMgASgJEgwKBHVzZXIYBCABKAliBnByb3RvMw=="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CommunicationModels.Models.Group), global::CommunicationModels.Models.Group.Parser, new[]{ "Title", "GroupKey", "UserGroupKey", "User" }, null, null, null, null)
                }));
        }
        #endregion

    }
    #region Messages
    public sealed partial class Group : pb::IMessage<Group>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<Group> _parser = new pb::MessageParser<Group>(() => new Group());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Group> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::CommunicationModels.Models.GroupReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Group()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Group(Group other) : this()
        {
            title_ = other.title_;
            groupKey_ = other.groupKey_;
            userGroupKey_ = other.userGroupKey_;
            user_ = other.user_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Group Clone()
        {
            return new Group(this);
        }

        /// <summary>Field number for the "title" field.</summary>
        public const int TitleFieldNumber = 1;
        private string title_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Title
        {
            get { return title_; }
            set
            {
                title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "groupKey" field.</summary>
        public const int GroupKeyFieldNumber = 2;
        private string groupKey_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string GroupKey
        {
            get { return groupKey_; }
            set
            {
                groupKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "userGroupKey" field.</summary>
        public const int UserGroupKeyFieldNumber = 3;
        private string userGroupKey_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string UserGroupKey
        {
            get { return userGroupKey_; }
            set
            {
                userGroupKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "user" field.</summary>
        public const int UserFieldNumber = 4;
        private string user_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string User
        {
            get { return user_; }
            set
            {
                user_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as Group);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Group other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Title != other.Title) return false;
            if (GroupKey != other.GroupKey) return false;
            if (UserGroupKey != other.UserGroupKey) return false;
            if (User != other.User) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Title.Length != 0) hash ^= Title.GetHashCode();
            if (GroupKey.Length != 0) hash ^= GroupKey.GetHashCode();
            if (UserGroupKey.Length != 0) hash ^= UserGroupKey.GetHashCode();
            if (User.Length != 0) hash ^= User.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Title.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Title);
      }
      if (GroupKey.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(GroupKey);
      }
      if (UserGroupKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UserGroupKey);
      }
      if (User.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(User);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Title.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(Title);
            }
            if (GroupKey.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(GroupKey);
            }
            if (UserGroupKey.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(UserGroupKey);
            }
            if (User.Length != 0)
            {
                output.WriteRawTag(34);
                output.WriteString(User);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Title.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
            }
            if (GroupKey.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(GroupKey);
            }
            if (UserGroupKey.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(UserGroupKey);
            }
            if (User.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(User);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Group other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Title.Length != 0)
            {
                Title = other.Title;
            }
            if (other.GroupKey.Length != 0)
            {
                GroupKey = other.GroupKey;
            }
            if (other.UserGroupKey.Length != 0)
            {
                UserGroupKey = other.UserGroupKey;
            }
            if (other.User.Length != 0)
            {
                User = other.User;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Title = input.ReadString();
            break;
          }
          case 18: {
            GroupKey = input.ReadString();
            break;
          }
          case 26: {
            UserGroupKey = input.ReadString();
            break;
          }
          case 34: {
            User = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            Title = input.ReadString();
                            break;
                        }
                    case 18:
                        {
                            GroupKey = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            UserGroupKey = input.ReadString();
                            break;
                        }
                    case 34:
                        {
                            User = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    #endregion

}

#endregion Designer generated code
